- name: Disable redis
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis v7
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update redis config file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update redis config file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: start redis service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes

- name: Check if Redis is listening on 0.0.0.0:6379
  ansible.builtin.shell: ss -ltnp | grep ':6379'
  register: redis_ports
  changed_when: false

- name: Verify Redis is responding on port 6379
  ansible.builtin.shell: |
    redis-cli -h 127.0.0.1 -p 6379 PING
  register: redis_ping
  changed_when: false


#print_head Disable redis
#dnf module disable redis -y
#dnf module enable redis:7 -y
#echo $?
#
#print_head install redis
#dnf install redis -y
#echo $?
#
#print_head update redis config file
#sed -i -e 's|127.0.0.1|0.0.0.0|' -e '/protected-mode/ c protected-mode no' /etc/redis/redis.conf
#echo $?
#
#systemctl enable redis
#systemctl start redis
#systemctl restart redis
#
#systemctl status redis
#echo $?