- name: Load Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Re-create a Frontend container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    recreate: true
    published_ports:
      - "80:80"
    restart_policy: always

    env:
      CATALOGUE_HOST: catalogue-dev.mikeydevops1.online
      CATALOGUE_PORT: "8080"
      USER_HOST: user-dev.mikeydevops1.online
      USER_PORT: "8080"
      CART_HOST: cart-dev.mikeydevops1.online
      CART_PORT: "8080"
      SHIPPING_HOST: shipping-dev.mikeydevops1.online
      SHIPPING_PORT: "8080"
      PAYMENT_HOST: payment-dev.mikeydevops1.online
      PAYMENT_PORT: "8080"