- name: Load Maven setup
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

#mysql -h mysql{{ env }}mikeydevops1.online -uroot -pRoboShop@1 < /app/db/schema.sql
#
#mysql -h mysql{{ env }}mikeydevops1.online -uroot -pRoboShop@1 < /app/db/app-user.sql
#
#mysql -h mysql{{ env }}mikeydevops1.online -uroot -pRoboShop@1 < /app/db/master-data.sql

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.mikeydevops1.online -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.mikeydevops1.online -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.mikeydevops1.online -uroot -pRoboShop@1 < /app/db/master-data.sql

