- name: Load Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Re-create a Shipping container
  community.docker.docker_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    state: started
    recreate: true
    published_ports:
      - "8080:8080"
    restart_policy: always

    env:
      CART_ENDPOINT: "cart-dev.mikeydevops1.online:8080"
      DB_HOST: "mysql-dev.mikeydevops1.online"




- name: Mysql setup-1 for Shipping
  community.docker.docker_container:
    name: Mysql-1
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: true

    restart_policy: always

    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/shipping"
      DB_HOST: "mysql-dev.mikeydevops1.online"
      DB_USER: "root"
      DB_PASS: "RoboShop@1"
      SCHEMA_FILE: "db/app-user.sql"


- name: Mysql setup-2 for Shipping
  community.docker.docker_container:
    name: Mysql-2
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: true

    restart_policy: always

    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/shipping"
      DB_HOST: "mysql-dev.mikeydevops1.online"
      DB_USER: "root"
      DB_PASS: "RoboShop@1"
      SCHEMA_FILE: "db/schema.sql "

- name: Mysql setup-3 for Shipping
  community.docker.docker_container:
    name: Mysql-3
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: true

    restart_policy: always

    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/shipping"
      DB_HOST: "mysql-dev.mikeydevops1.online"
      DB_USER: "root"
      DB_PASS: "RoboShop@1"
      SCHEMA_FILE: "db/master-data.sql"

