- name: Load Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Re-create a catalogue container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    recreate: true
    published_ports:
      - "8080:8080"
    restart_policy: always

    env:
      MONGO: "true"
      MONGO_URL: "mongodb://mongo-dev.mikeydevops1.online:27017/catalogue"


- name: Load Schema for catalogue
  community.docker.docker_container:
    name: "catalogue-schema"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: true
    restart_policy: always
    env:
      DB_TYPE: "mongo"
      APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/catalogue"
      DB_HOST: "mongo-dev.mikeydevops1.online"
      SCHEMA_FILE: "db/master-data.js"


