#dnf install python3 gcc python3-devel -y
#app_pre_req
#artificat_download
#cd /app
#pip3 install -r requirements.txt
#
#systemmd_setup

#- name: Install Python Packages
#  ansible.builtin.dnf:
#    name:
#      - python3
#      - gcc
#      - python3-devel
#    state: present
#
#- name: Show current working directory
#  ansible.builtin.command: pwd
#  register: pwd_output
#
#- name: Display pwd result
#  ansible.builtin.debug:
#    var: pwd_output.stdout
#
#- name: Include systemd file
#  ansible.builtin.include_tasks:
#    file: artifact_download.yml
#
#
#- name: Include systemd file
#  ansible.builtin.include_tasks:
#    file: systemd_setup.yml
#
#
#
#- name: Install NodeJs Dependencies
#  ansible.builtin.command: pip3 install -r requirements.txt
#  args:
#    chdir: /app



- name: Install Python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: installed

- name: Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml


- name: Install Python Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app



















